### ISSUE TITLE
talib的out of index错误

### ISSUE THREAD

**Issue by wondereamer** [QuantFans/quantdigger#1]
在策略运行完用matplotlib显示后，鼠标右移超过最右边的bar会显示该错误。可能talib的运行结果与
显示挂钩了。

**Comment by ongbe** [comment]
def format_coord(self, x, y):
         """ 状态栏信息显示 """
-        index = x
+        index = x - 1
         f = x % 1
         index = x-f if f < 0.5 else x-f+1
         #print len(self.kwindow.rects.get_array())

**Comment by wondereamer** [comment]
谢谢！回头我试试。
