### ISSUE TITLE
应该是有一些模块还没有上传吧？

### ISSUE THREAD

**Issue by fashionwu** [QuantFans/quantdigger#12]
from quantdigger.engine.strategy import TradingStrategy
from quantdigger.util import  pcontract, stock
这些模块貌似都没有上传啊

**Comment by wondereamer** [comment]
上传了啊

**Comment by fashionwu** [comment]
engine目录下没有strategy模块，util模块下没有pcontract, stock模块，你可以检查下看

**Comment by wondereamer** [comment]
哦，那个是旧代码，你是怎么安装quantdigger的？

**Comment by fashionwu** [comment]
python install.py 安装的，我那是运行的backup里面的代码，是旧代码，还没有清理的，那就应该没有关系了。

**Comment by wondereamer** [comment]
你是什么系统安装的，能正常使用吗？有朋友安装出现了问题。

**Comment by fashionwu** [comment]
我的是windows安装的，中途手动安装了python2.7的windows vc编译器， VCForPython27.msi，顺便说一下，python2.6是有语法错误的：sys.version_info.major ，在python2.6没有major

**Comment by wondereamer** [comment]
了解，谢谢反馈～
