### ISSUE TITLE
no module named plotting 

### ISSUE THREAD

**Issue by xgdgsc** [QuantFans/quantdigger#4]
the `import plotting` in demo shows the error `no module named plotting`.

**Comment by wondereamer** [comment]
Thanks for feed back. It's fixed in the latest version. https://pypi.python.org/pypi/QuantDigger/0.154

**Comment by xgdgsc** [comment]
After update shows following error:
ImportError: No module named kernel.engine.execute_unit

**Comment by wondereamer** [comment]
have you setted environment varaible PYTHONPATH ?

**Comment by xgdgsc** [comment]
After all, it is because I named the file for testing quantdigger.py which conflicts with the package name.
