### ISSUE TITLE
安装pip出错，installed,plese add pip to your path

### ISSUE THREAD

**Issue by evander1995** [QuantFans/quantdigger#41]
安装时出现：
----------- install QuantDigger --------------
----------- install pip --------------
pip no install
============ downloading pip-6.0.8.tar.gz from:https://pypi.python.org/packages/source/p/pip/pip-6.0.8.tar.gz
============ extracting pip-6.0.8.tar.gz
============ installing pip
**============ installed,plese add pip to your path**

我尝试过python2.7.13和3.6版本，尝试手动安装pip6.0.8版本，也尝试过用anaconda2、3，同样会出现这样的提示。

**Comment by qink1986** [comment]
pip本来就有了啊。。。

**Comment by evander1995** [comment]
@qink1986 是本来就有，但是这个上面的提示意思不是pip没有安装吗？然后他下载了一个6.0.8的版本，然后这个版本跟我自带的版本不对，我把新版本卸载了安装成了旧版本问题依然存在。

**Comment by qink1986** [comment]
用的什么命令会出这个提示？没见过

**Comment by evander1995** [comment]
用的这个命令，windows10下，
C:\Users\Administrator\Desktop\quantdigger\setupscripts>C:\ProgramData\Anaconda2\python.exe install.py install

**Comment by evander1995** [comment]
@qink1986 
用的这个命令，windows10下，
C:\Users\Administrator\Desktop\quantdigger\setupscripts>C:\ProgramData\Anaconda2\python.exe install.py install

**Comment by qink1986** [comment]
============ installed,plese add pip to your path
不是说已经装好了么？
pip没添加到环境变量吧，Python也是

**Comment by evander1995** [comment]
@qink1986 对就是这个问题，搞定了，谢谢！
